services:

  consumer-edc:
    container_name: "consumer-edc"
    image: ghcr.io/possible-x/connector:latest-develop
    env_file: "secrets/edc_ionos_secrets.txt"
    volumes:
      - ./initial_data/edc/consumer.properties:/app/dataspaceconnector-configuration.properties:ro
      - ./initial_data/edc/consumer.pfx:/opt/edc.pfx:ro
    entrypoint: >
      /bin/sh -c '
      touch /opt/vault.properties;
      java -Dedc.fs.config=/app/dataspaceconnector-configuration.properties -jar /app/connector.jar
      '
    network_mode: "host"
    depends_on:
      postgres:
        condition: service_healthy

  provider-edc:
    container_name: "provider-edc"
    image: ghcr.io/possible-x/connector:latest-develop
    env_file: "secrets/edc_ionos_secrets.txt"
    volumes:
      - ./initial_data/edc/provider.properties:/app/dataspaceconnector-configuration.properties:ro
      - ./initial_data/edc/provider.pfx:/opt/edc.pfx:ro
    entrypoint: >
      /bin/sh -c '
      touch /opt/vault.properties;
      java -Dedc.fs.config=/app/dataspaceconnector-configuration.properties -jar /app/connector.jar 
      '
    network_mode: "host"
    depends_on:
      postgres:
        condition: service_healthy
  
  omejdn-server:
    user: "${UID}:${GID}"
    container_name: "omejdn-server"
    image: ghcr.io/possible-x/omejdn:0.1.1
    environment:
      OMEJDN_ISSUER: "http://localhost:4567"
      OMEJDN_FRONT_URL: "http://localhost:4567"
      OMEJDN_OPENID: true
      OMEJDN_ENVIRONMENT: "development"
      OMEJDN_ACCEPT_AUDIENCE: idsc:IDS_CONNECTORS_ALL
      OMEJDN_DEFAULT_AUDIENCE: idsc:IDS_CONNECTORS_ALL
      OMEJDN_PLUGINS: plugins_config/plugins.yml
    volumes:
      - ./docker_data/omejdn/config:/opt/config
      - ./initial_data/omejdn/plugins_config/plugins.yml:/opt/plugins_config/plugins.yml:ro
      - ./docker_data/omejdn/keys:/opt/keys
      - ./initial_data/omejdn/config/:/opt/initial_config/:ro
      - ./initial_data/omejdn/keys/:/opt/initial_keys:ro
    entrypoint: >
      /bin/bash -c '
      cp -n /opt/initial_config/initial_clients.yml /opt/config/clients.yml;
      cp -rf /opt/initial_config/scope_mapping.yml /opt/config/scope_mapping.yml;
      cp -r -n /opt/initial_keys/* /opt/keys/;
      ruby omejdn.rb
      '
    network_mode: "host"
    restart: on-failure

  sd-creation-wizard-api:
    container_name: "sd-creation-wizard-api"
    image: ghcr.io/possible-x/catalog-shapes/sd-creation-wizard-api:latest-develop
    ports:
      - "8085:8080"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.admin
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    volumes:
      - ./initial_data/pgadmin/servers.json:/pgadmin4/servers.json:ro
    entrypoint: >
      /bin/sh -c '
      echo "postgres:5432:*:postgres:postgres" > /tmp/pgpass;
      chmod 600 /tmp/pgpass;
      /entrypoint.sh
      '
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
  
  postgres:
    user: "${UID}:${GID}"
    container_name: "postgres_possible"
    hostname: postgres
    image: postgres:16
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 5s
      retries: 50
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - ./docker_data/postgres/data:/var/lib/postgresql/data
      - ./initial_data/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./initial_data/postgres/init-edc-db.sql:/opt/init-edc-db.sql:ro

  did-web-service:
    container_name: "did-web-service"
    image: ghcr.io/possible-x/did-web-service:latest
    environment:
      SPRING_DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver
      SPRING_JPA_DATABASEPLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/didwebservice
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    network_mode: "host"
    healthcheck:
      test: wget --no-check-certificate https://localhost:4443/health || exit 1
      interval: 30s
      timeout: 30s
      retries: 50
      start_period: 3s
    depends_on:
      postgres:
        condition: service_healthy

  # ============== piveau ==============
  piveau-hub-repo:
    image: ghcr.io/possible-x/piveau-mirror/piveau-hub-repo:2025-02-03
    container_name: piveau-hub-repo
    hostname: piveau-hub-repo
    user: "${UID}:${GID}"
    logging:
      options:
        max-size: "50m"
    ports:
      - 5081:8080
      - 5085:8085   # http shell
      #- 5002:5000  # telnet
    environment:
      - PIVEAU_HUB_API_KEY=yourRepoApiKey
      - PIVEAU_LOG_LEVEL=DEBUG
      - JAVA_OPTS=-Xms1g -Xmx2g
    volumes:
      - ./initial_data/fh-config/repo-hub-conf.json:/usr/verticles/conf/config.json:ro
      - ./initial_data/fh-config/shapes:/usr/verticles/conf/shapes:ro
      - ./docker_data/piveau-hub-repo/trust:/usr/verticles/trust

  piveau-hub-search:
    image: ghcr.io/possible-x/piveau-mirror/piveau-hub-search:2025-02-03
    container_name: piveau-hub-search
    hostname: piveau-hub-search
    logging:
      options:
        max-size: "50m"
    ports:
      - 5082:8080
      - 5086:8081
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - PIVEAU_HUB_SEARCH_API_KEY=yourSearchApiKey
      - PIVEAU_LOG_LEVEL=DEBUG
      - JAVA_OPTS=-Xms1g -Xmx2g
    volumes:
      - ./initial_data/fh-config/repo-search-conf.json:/usr/verticles/conf/config.json
      - ./initial_data/fh-config/shapes:/usr/verticles/conf/shapes:ro

  piveau-hub-ui:
    image: ghcr.io/possible-x/piveau-mirror/piveau-hub-ui:2025-02-03
    container_name: piveau-hub-ui
    hostname: piveau-hub-ui
    logging:
      options:
        max-size: "50m"
    ports:
      - 5080:8080
    environment:
      - VITE_METADATA_TITLE=Local Possible Catalog
      - VITE_API_BASE_URL=http://localhost:5082/
      - VITE_API_HUB_URL=http://localhost:5081/
    volumes:
      - ./initial_data/fh-config/user-config.js:/app/apps/vanilla-piveau-hub-ui/config/user-config.js:ro
      - ./initial_data/fh-config/en.json:/app/apps/vanilla-piveau-hub-ui/config/i18n/lang/en.json:ro

  piveau-hub-normalization:
    image: ghcr.io/possible-x/piveau-mirror/normalization-urdna2015:2025-02-03
    container_name: piveau-hub-normalization
    hostname: piveau-hub-normalization
    ports:
      - 8089:8080
    env_file: "secrets/vc_signing_key.txt"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.16
    container_name: elasticsearch
    hostname: elasticsearch
    user: "${UID}:${GID}"
    logging:
      options:
        max-size: "50m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: curl -s -f http://elasticsearch:9200/_cat/health >/dev/null || exit 1
      interval: 5s
      timeout: 3s
      retries: 20
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms2G -Xmx4G
    volumes:
      - ./docker_data/elasticsearch:/usr/share/elasticsearch/data

  virtuoso:
    image: openlink/virtuoso-opensource-7:7.2.9
    container_name: virtuoso
    hostname: virtuoso
    user: "${UID}:${GID}"
    logging:
      options:
        max-size: "50m"
    ports:
      - 8890:8890
      - 1111:1111
    environment:
      - DBA_PASSWORD=dba
      - VIRT_PARAMETERS_NUMBEROFBUFFERS=170000
      - VIRT_PARAMETERS_MAXDIRTYBUFFERS=130000
      - VIRT_PARAMETERS_SERVERTHREADS=100
      - VIRT_HTTPSERVER_SERVERTHREADS=100
      - VIRT_HTTPSERVER_MAXCLIENTCONNECTIONS=100
    volumes:
      - ./docker_data/virtuoso:/database