services:
  piveau-hub-repo:
    image: dockerhub.fokus.fraunhofer.de:5000/piveau/hub/piveau-hub-repo:latest
    container_name: piveau-hub-repo
    hostname: piveau-hub-repo
    user: "${UID}:${GID}"
    logging:
      options:
        max-size: "50m"
    ports:
      - 5081:8080
      - 5085:8085   # http shell
      #- 5002:5000  # telnet
    environment:
      - PIVEAU_HUB_API_KEY=yourRepoApiKey
      - PIVEAU_LOG_LEVEL=DEBUG
      - JAVA_OPTS=-Xms1g -Xmx2g
    volumes:
      - ./initial_data/fh-config/repo-hub-conf.json:/usr/verticles/conf/config.json:ro
      - ./initial_data/fh-config/shapes:/usr/verticles/conf/shapes:ro
      - ./docker_data/piveau-hub-repo/trust:/usr/verticles/trust

  piveau-hub-search:
    image: dockerhub.fokus.fraunhofer.de:5000/piveau/hub/piveau-hub-search:latest
    container_name: piveau-hub-search
    hostname: piveau-hub-search
    logging:
      options:
        max-size: "50m"
    ports:
      - 5082:8080
      - 5086:8081
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - PIVEAU_HUB_SEARCH_API_KEY=yourSearchApiKey
      - PIVEAU_LOG_LEVEL=DEBUG
      - JAVA_OPTS=-Xms1g -Xmx2g
    volumes:
      - ./initial_data/fh-config/repo-search-conf.json:/usr/verticles/conf/config.json
      - ./initial_data/fh-config/shapes:/usr/verticles/conf/shapes:ro

  piveau-hub-ui:
    image: ghcr.io/possible-x/catalog-ui:1407a3bc48b972278b15d4ca89f82a604ad0fc3b
    container_name: piveau-hub-ui
    hostname: piveau-hub-ui
    logging:
      options:
        max-size: "50m"
    ports:
      - 5080:8080
    environment:
      - VITE_METADATA_TITLE=Local Possible Catalog
      - VITE_API_BASE_URL=http://localhost:5082/
      - VITE_API_HUB_URL=http://localhost:5081/
    volumes:
      - ./initial_data/fh-config/user-config.js:/app/apps/vanilla-piveau-hub-ui/config/user-config.js:ro
      - ./initial_data/fh-config/en.json:/app/apps/vanilla-piveau-hub-ui/config/i18n/lang/en.json:ro

  piveau-hub-normalization:
    image: dockerhub.fokus.fraunhofer.de:5000/possible/normalization-urdna2015:latest
    container_name: piveau-hub-normalization
    hostname: piveau-hub-normalization
    ports:
      - 8089:8080
    env_file: "secrets/vc_signing_key.txt"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.16
    container_name: elasticsearch
    hostname: elasticsearch
    user: "${UID}:${GID}"
    logging:
      options:
        max-size: "50m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: curl -s -f http://elasticsearch:9200/_cat/health >/dev/null || exit 1
      interval: 5s
      timeout: 3s
      retries: 20
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms2G -Xmx4G
    volumes:
      - ./docker_data/elasticsearch:/usr/share/elasticsearch/data

  virtuoso:
    image: openlink/virtuoso-opensource-7:7.2.9
    container_name: virtuoso
    hostname: virtuoso
    user: "${UID}:${GID}"
    logging:
      options:
        max-size: "50m"
    ports:
      - 8890:8890
      - 1111:1111
    environment:
      - DBA_PASSWORD=dba
      - VIRT_PARAMETERS_NUMBEROFBUFFERS=170000
      - VIRT_PARAMETERS_MAXDIRTYBUFFERS=130000
      - VIRT_PARAMETERS_SERVERTHREADS=100
      - VIRT_HTTPSERVER_SERVERTHREADS=100
      - VIRT_HTTPSERVER_MAXCLIENTCONNECTIONS=100
    volumes:
      - ./docker_data/virtuoso:/database
